apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    url: postgres:5432
    user: de_user
    isDefault: true

    jsonData:
      database: sensordb
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false

    secureJsonData:
      password: de_pass