{
 "title": "Environment Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Current Environmental Index Overview",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sensordb",
     "rawSql": "SELECT DISTINCT ON (device_id)\n  CASE\n    WHEN device_id = '00:0f:00:70:91:0a' THEN 'Urban Park'\n    WHEN device_id = '1c:bf:ce:15:ec:4d' THEN 'Residential Area'\n    WHEN device_id = 'b8:27:eb:bf:9d:51' THEN 'Downtown Traffic Area'\n  END AS location,\n  environmental_index_avg\nFROM processed_environmental_readings\nORDER BY device_id, processed_ts DESC;"
    }
   ]
  },
  {
   "title": "Environmental Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "sensordb",
     "rawSql": "SELECT\n  alert_ts AS \"Time\",\n\n  CASE\n    WHEN device_id = '00:0f:00:70:91:0a' THEN 'Urban Park'\n    WHEN device_id = '1c:bf:ce:15:ec:4d' THEN 'Residential Area'\n    WHEN device_id = 'b8:27:eb:bf:9d:51' THEN 'Downtown Traffic Area'\n  END AS \"Location\",\n\n  previous_status || ' → ' || current_status AS \"Status Change\",\n\n  environmental_index_avg AS \"Index\"\n\nFROM environmental_alerts\nORDER BY alert_ts DESC;"
    }
   ]
  },
  {
   "title": "Environmental Index Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "sensordb",
     "rawSql": "SELECT\n  processed_ts AS \"time\",\n  MAX(CASE WHEN device_id = '00:0f:00:70:91:0a' THEN environmental_index_avg END) AS \"Urban Park\",\n  MAX(CASE WHEN device_id = '1c:bf:ce:15:ec:4d' THEN environmental_index_avg END) AS \"Residential Area\",\n  MAX(CASE WHEN device_id = 'b8:27:eb:bf:9d:51' THEN environmental_index_avg END) AS \"Downtown Traffic Area\"\nFROM processed_environmental_readings\nGROUP BY processed_ts\nORDER BY time;"
    }
   ]
  }
 ]
}